//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 03:35:02 PM CET 
//


package SC13Project.Milestone1.HotelReservation.Database;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stayPeriodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stayPeriodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="checkin" type="{http://www.example.org/HotelDB}ReservationDateInfo"/>
 *         &lt;element name="checkout" type="{http://www.example.org/HotelDB}ReservationDateInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stayPeriodType", propOrder = {
    "checkin",
    "checkout"
})
public class StayPeriodType {

    @XmlElement(required = true)
    protected ReservationDateInfo checkin;
    @XmlElement(required = true)
    protected ReservationDateInfo checkout;

    /**
     * Gets the value of the checkin property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationDateInfo }
     *     
     */
    public ReservationDateInfo getCheckin() {
        return checkin;
    }

    /**
     * Sets the value of the checkin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationDateInfo }
     *     
     */
    public void setCheckin(ReservationDateInfo value) {
        this.checkin = value;
    }

    /**
     * Gets the value of the checkout property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationDateInfo }
     *     
     */
    public ReservationDateInfo getCheckout() {
        return checkout;
    }

    /**
     * Sets the value of the checkout property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationDateInfo }
     *     
     */
    public void setCheckout(ReservationDateInfo value) {
        this.checkout = value;
    }

}
