//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 03:30:54 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/warehouse", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package SC13Project.Milestone1.Warehouse.Database;
